name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.4"]
        ghc: ["8.10.3"]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: haskell/actions/setup@v1.2
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}
      - uses: actions/cache@v2.1.3
        with:
          path: |
            ${{ steps.setup-haskell.outputs.stack-root }}
            .stack-work
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('stack.yaml.lock', 'colour-palette.cabal')}}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-
      - run: stack build --pedantic # --test
      # - run: stack test
